# Generated by Django 3.2.10 on 2023-01-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_details',
            name='c_email',
        ),
    ]
