# Generated by Django 3.2.10 on 2023-01-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_shop', '0002_remove_seller_details_c_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_master',
            name='strapcolor',
        ),
    ]
